### PR TITLE
try to use cdt-package to enable qtopengl

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mingwandroid** [comment]
@lomereiter If this works that was easy ..

**Comment by looooo** [comment]
didn't work. I have seen similar problems also with other opengl-dependent builds. I am definetly interested in how to solve them:
```
checking for OpenGL... 
x86_64-conda_cos6-linux-gnu-c++ -c -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/conda/feedstock_root/build_artifacts/qt_1542321033823/_h_env/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/qt_1542321033823/work=/usr/local/src/conda/qt-5.6.2 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/qt_1542321033823/_h_env=/usr/local/src/conda-prefix -std=c++11 -Wno-expansion-to-defined -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -DXK_dead_currency=0xfe6f -DXK_ISO_Level5_Lock=0xfe13 -DFC_WEIGHT_EXTRABLACK=215 -DFC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -DGLX_GLXEXT_PROTOTYPES -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/conda/feedstock_root/build_artifacts/qt_1542321033823/_h_env/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/qt_1542321033823/work=/usr/local/src/conda/qt-5.6.2 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/qt_1542321033823/_h_env=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -DXK_dead_currency=0xfe6f -DXK_ISO_Level5_Lock=0xfe13 -DFC_WEIGHT_EXTRABLACK=215 -DFC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -DGLX_GLXEXT_PROTOTYPES -pipe -O2 -Wall -W -fPIC  -I. -I/home/conda/feedstock_root/build_artifacts/qt_1542321033823/_h_env/include -I/usr/include/libdrm -I../../../mkspecs/linux-g++ -o opengldesktop.o opengldesktop.cpp
x86_64-conda_cos6-linux-gnu-c++ -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,-rpath,/home/conda/feedstock_root/build_artifacts/qt_1542321033823/_h_env/lib -L/home/conda/feedstock_root/build_artifacts/qt_1542321033823/_h_env/lib -Wl,-rpath-link,/home/conda/feedstock_root/build_artifacts/qt_1542321033823/_h_env/lib -Wl,-O1 -o opengldesktop opengldesktop.o   -lGL 
<path_to_ld>: warning: libglapi.so.0, needed by <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so, not found (try using -rpath or -rpath-link)
<path_to_ld>: warning: libselinux.so.1, needed by <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so, not found (try using -rpath or -rpath-link)
<path_to_ld>: warning: libXdamage.so.1, needed by <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so, not found (try using -rpath or -rpath-link)
<path_to_ld>: warning: libXfixes.so.3, needed by <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so, not found (try using -rpath or -rpath-link)
<path_to_ld>: warning: libXxf86vm.so.1, needed by <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so, not found (try using -rpath or -rpath-link)
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `XDamageAdd'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `_glapi_check_multithread'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `_glapi_get_proc_address'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `XF86VidModeQueryVersion'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `XF86VidModeGetModeLine'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `XFixesDestroyRegion'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `_glapi_get_dispatch_table_size'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `_glapi_get_proc_offset'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `XFixesCreateRegion'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `XDamageQueryVersion'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `_glapi_tls_Dispatch'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `_glapi_set_dispatch'
<path_to_ld>: <build_env>/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libGL.so: undefined reference to `_glapi_set_context'
collect2: error: ld returned 1 exit status
gmake: *** [opengldesktop] Error 1
OpenGL disabled.
```

I edited the paths to make this output a bit more readable.

**Comment by mingwandroid** [comment]
yum whatprovides

**Comment by mingwandroid** [comment]
Yeah, pinging @isuruf. I had a look in some feedstocks and couldn't find it.

**Comment by mingwandroid** [comment]
Not sure about yum requirements, installing them anyway may not be harmful (but then again)

**Comment by isuruf** [comment]
It's not clear what you want to do.

If you want to use cdt packages only for gcc7 build, add,
```
- {{ cdt('foo') }}   # [c_compiler == 'gcc']
```

If you don't want that and wants the yum package, adding a `yum_requirements.txt` and rerendering would install them in the docker image

**Comment by isuruf** [comment]
@mingwandroid, would you mind creating a `mesagl-libglapi` CDT package and uploading it? (It seems only a ppc64le CDT package is available.)

**Comment by mingwandroid** [comment]
Sure thing @isuruf. Sorry for the oversight.

**Comment by mingwandroid** [comment]
Ah seems:

```
yum whatprovides **/libglapi.so.0
Loaded plugins: fastestmirror, ovl
base                                                                                                                                                                                                                   | 3.7 kB     00:00     
base/primary_db                                                                                                                                                                                                        | 4.7 MB     00:00     
extras                                                                                                                                                                                                                 | 3.4 kB     00:00     
extras/primary_db                                                                                                                                                                                                      |  26 kB     00:00     
updates                                                                                                                                                                                                                | 3.4 kB     00:00     
updates/primary_db                                                                                                                                                                                                     | 1.9 MB     00:00     
base/filelists_db                                                                                                                                                                                                      | 6.4 MB     00:01     
extras/filelists_db                                                                                                                                                                                                    |  24 kB     00:00     
updates/filelists_db                                                                                                                                                                                                   | 1.3 MB     00:00     
mesa-dri-drivers-11.0.7-4.el6.i686 : Mesa-based DRI drivers
Repo        : base
Matched from:
Filename    : /usr/lib/libglapi.so.0



mesa-dri-drivers-11.0.7-4.el6.x86_64 : Mesa-based DRI drivers
Repo        : base
Matched from:
Filename    : /usr/lib64/libglapi.so.0
```

so `{{ cdt('mesa-dri-drivers') }}` should be what you need here.

**Comment by mingwandroid** [comment]
Looking good?!

**Pull request merged**
