### PR TITLE
Update to 5.12.5

### PR DESCRIPTION
**Pull request by jschueller**
same as #116, but for 5.12.5 that was just released, to see if it passes too

### CODE REVIEW

**Comment by jschueller** [comment]
hi @ocefpaf, any news from the windows build ?

**Comment by ocefpaf** [comment]
Travelling at the moment. I'll put it to build this night and report tomorrow morning.

**Comment by isuruf** [comment]
@msarahan, @mingwandroid can you build this on windows with windows SDK `>=10.0.16299.0,<=10.0.17763.0`? (We need to avoid `10.0.18362.0` as Qt seems to be hardcoding the SDK path in their object files and azure doesn't have that.)

**Comment by ocefpaf** [comment]
> hi @ocefpaf, any news from the windows build ?

@jschueller I'll have to find another Windows machine. I have ~100G available but I'm running out of space with this build! (Things seems to be working though.)

**Comment by mingwandroid** [comment]
How do I build this? I'll kick off a build and go to sleep!

**Comment by ocefpaf** [comment]
> How do I build this? I'll kick off a build and go to sleep!

Yep. I made two attempts today, ~5 hours each.

**Comment by mingwandroid** [comment]
Is this enough:

```
set CONDA_CHANNEL_PRIORITY=strict
conda.exe build recipe -m .ci_support\win_cxx_compilervs2015vc14.yaml -c conda-forge -c defaults
```

Seems to be ticking along!

**Comment by isuruf** [comment]
@mingwandroid, do you have a windows machine with `10.0.17763.0` as the highest windows SDK?
If so, you can do, `conda build recipe -m .ci_support/win_cxx_compilervs2015vc14.yaml`

**Comment by mingwandroid** [comment]
Great, thanks @isuruf. Already running!

I do have such a machine, two (but the server is too noisy and in my bedroom so not appropriate for overnight runs).

**Comment by mingwandroid** [comment]
For AD, I always had to do Qt builds in shallow prefixes, (C:\qt5b was my go-to location, with `--croot C:\qt5b--no-build-id`).

Do we know that's no longer the case? My build is currently proceeding in `C:\opt\conda\conda-bld\qt_1569192553801\_h_env` and I am considering restarting it.

**Comment by isuruf** [comment]
Yes, I forgot. Last time I built it (5.12.1), I had to do `CONDA_BLD_PATH=C:\\bld`.

**Comment by mingwandroid** [comment]
OK, restarting then

**Comment by mingwandroid** [comment]
Well, my build succeeded but some WIP changes I had to conda-build deleted the archive! It is rebuilding now.

**Comment by mingwandroid** [comment]
Well, my build succeeded but some WIP changes I had to conda-build deleted the archive! I kicked off a rebuild and that pulled clang 9 in instead. My computer then crashed mid-build! Going to fire up the server now.

**Comment by mingwandroid** [comment]
From my logs I saw this, it looks a bit suspect:

```
../../3rdparty/chromium\third_party/boringssl/src/include/openssl/base.h(147): warning C4005: 'OPENSSL_VERSION_NUMBER': macro redefinition
C:/qt5b/_h_env/Library/include\openssl/opensslv.h(42): note: see previous definition of 'OPENSSL_VERSION_NUMBER'
```

Mostly just making a note of it in case anyone searches for this string.

**Comment by mingwandroid** [comment]
Test build being uploaded. Log at:

https://drive.google.com/file/d/1-SzAITSUWkpER4oe4wGvHKWYoJhA3V6b/view?usp=sharing

Cheers.

**Comment by jschueller** [comment]
thanks!

**Comment by isuruf** [comment]
It was @mingwandroid who built it on windows. I only uploaded it.

**Pull request merged**
