### PR TITLE
Restore web widgets in macOS

### PR DESCRIPTION
**Pull request by ccordoba12**
Also add a test to verify that the library was built correctly

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@isuruf, I don't understand the failures on Linux. Could you take a look at them? Thanks!

**Comment by ccordoba12** [comment]
> Why do you want webkit instead of webengine?

I couldn't manage to compile Webengine in Circle. I thought it required the 10.7 sdk (which is impossible to use the new compilers), so I went for Webkit instead, which is far more simpler.

Of course, I don't want to deviate from defaults, but I also don't have more time to take a look at this. So your help is really appreciated.

**Comment by pgunn** [comment]
@ccordoba12 @mingwandroid Hi, any news on this?

**Comment by mingwandroid** [comment]
Anaconda Distribution provides qt 5.9 at present and I am actively working on updating to 5.12.

Conda-forge are very far behind now unfortunately! I will see if I we can allocate some of my time to try to update conda-forge afterwards but we'd probably like to get the compiler migration out of the way first.

**Comment by ccordoba12** [comment]
@mingwandroid, if you're ok with it, I'd like to merge this one to help Spyder conda-forge users in the meantime (Spyder is broken with the current macOS packages).

**Comment by mingwandroid** [comment]
@ccordoba12 100%, go for it.

**Comment by ccordoba12** [comment]
Thanks! Merging then.

Note: The Linux failures are unrelated to these changes, as far as I can tell.

**Comment by ccordoba12** [comment]
@pgunn, a PyQt5 recompilation is still required.

**Comment by pgunn** [comment]
@ccordoba12 Is there someone I should poke about that?

**Comment by ccordoba12** [comment]
@pgunn, please see https://github.com/conda-forge/pyqt-feedstock/pull/43

**Pull request merged**
