### PR TITLE
use jinja2 in url

### PR DESCRIPTION
**Pull request by CJ-Wright**
This should help the bot to find new versions.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
Closing since it won't build

**Comment by ocefpaf** [comment]
Still worth merging, no?

**Comment by CJ-Wright** [comment]
I thought we had to build qt ourselves, it wouldn't fit in the time allotment?

**Comment by ocefpaf** [comment]
> I thought we had to build qt ourselves, it wouldn't fit in the time allotment?

Yep. But I guess the change is still nice to have in the recipe, no?

> I don't know if this is worth going through the trouble of building, for a rather cosmetic change. However, I opened an issue so next time we do build this we can update the url then.

We can do `skip ci`.

**Comment by CJ-Wright** [comment]
@ocefpaf would you mind taking over this PR?

**Comment by ocefpaf** [comment]
Cool. No `ci skip` command works with Azure Pipelines and I cannot cancel it :smile: 

Merging it and, if macOS produces a package, we can wither remove it or leave it. No big deal.

**Comment by CJ-Wright** [comment]
Thank you!

**Comment by CJ-Wright** [comment]
The bot should send a 5.13 PR sometime soon-ish.

**Comment by isuruf** [comment]
This PR failed tests on OSX and should not have been merged.

**Comment by ocefpaf** [comment]
> This PR failed tests on OSX and should not have been merged.

Are those failures related to the Jinja change? That is quite odd!

**Comment by isuruf** [comment]
No, related to the rerender. (both osx and windows)

**Pull request merged**
