### PR TITLE
Rebuild to fix gstreamer and gst-plugins pins

### PR DESCRIPTION
**Pull request by duncanmmacleod**
Somehow the latest build is pinned against gstreamer 1.18 and gst-plugins-base 1.14 - those packages come from the same recipe so this is broken:

```console
$ conda search --info qt=5.12.9=*_2
Loading channels: done
qt 5.12.9 h9d6b050_2
--------------------
file name   : qt-5.12.9-h9d6b050_2.tar.bz2
name        : qt
version     : 5.12.9
build       : h9d6b050_2
build number: 2
size        : 99.5 MB
license     : LGPL-3.0-only
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/qt-5.12.9-h9d6b050_2.tar.bz2
md5         : 2f7c14748e3d98ff1ff27cadffb34d97
timestamp   : 2020-12-22 07:35:15 UTC
dependencies:
  - dbus >=1.13.6,<2.0a0
  - expat >=2.2.9,<2.3.0a0
  - fontconfig >=2.13.1,<3.0a0
  - freetype >=2.10.4,<3.0a0
  - gst-plugins-base >=1.14.4,<1.15.0a0
  - gstreamer >=1.18.2,<1.19.0a0
  - icu >=68.1,<69.0a0
  - jpeg >=9d,<10a
  - libclang >=11.0.0,<12.0a0
  - libevent >=2.1.10,<2.1.11.0a0
  - libgcc-ng >=9.3.0
  - libglib >=2.66.4,<3.0a0
  - libpng >=1.6.37,<1.7.0a0
  - libpq >=12.3,<13.0a0
  - libstdcxx-ng >=9.3.0
  - libxcb
  - libxkbcommon >=1.0.3,<2.0a0
  - libxml2 >=2.9.10,<2.10.0a0
  - mysql-libs >=8.0.22,<8.0.23.0a0
  - nspr >=4.29,<5.0a0
  - nss >=3.60,<4.0a0
  - openssl >=1.1.1i,<1.1.2a
  - sqlite >=3.34.0,<4.0a0
  - zlib >=1.2.11,<1.3.0a0
```

So, this PR just regenerates the feedstock, which fixes the pinnings.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by duncanmmacleod** [comment]
@conda-forge/qt, this is an annoying issue for me, the following currently fails:

```console
$ conda create -n __test gstreamer=1.18.3 gst-plugins-base=1.18.3 qt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package gstreamer conflicts for:
gstreamer=1.18.3
qt -> gstreamer[version='>=1.12.4,<1.13.0a0|>=1.12.5,<1.13.0a0|>=1.14.4,<1.15.0a0|>=1.18.2,<1.19.0a0|>=1.14.0,<1.15.0a0']
qt -> gst-plugins-base[version='>=1.14.4,<1.15.0a0'] -> gstreamer[version='>=1.12.2,<1.13.0a0|>=1.14.0,<2.0a0|>=1.14.1,<2.0a0|>=1.14.4,<2.0a0|>=1.14.5,<2.0a0']

Package gst-plugins-base conflicts for:
gst-plugins-base=1.18.3
qt -> gst-plugins-base[version='>=1.12.2,<1.13.0a0|>=1.12.4,<1.13.0a0|>=1.12.5,<1.13.0a0|>=1.14.4,<1.15.0a0|>=1.14.0,<1.15.0a0']
```

The CI seems to fail all the time, and it fails for me locally. Is someone able to review this and help me get it merged?

**Comment by duncanmmacleod** [comment]
@conda-forge/core, is someone able to (a) confirm that this is real problem, and (b) coax the CI to pass so this can be merged? Thanks.

**Comment by chrisburr** [comment]
> coax the CI to pass so this can be merged? Thanks.

We end up building this locally and uploading using the procedure in [CFEP-03](https://github.com/conda-forge/cfep/blob/master/cfep-03.md). If someone who maintains this recipe can take a look and merge I can take care of building macOS and Linux. Someone else will have to look at Windows as I don't have access to a suitable machine.

**Comment by duncanmmacleod** [comment]
> Someone else will have to look at Windows as I don't have access to a suitable machine.

I have a windows machine, I have no idea if 'any windows machine' is what you're after, but please let me know if I can help get this through.

Thanks @chrisburr!

**Comment by duncanmmacleod** [comment]
> If someone who maintains this recipe can take a look and merge I can take care of building macOS and Linux

@conda-forge/qt, can someone please review and merge this trivial change, please?

**Comment by isuruf** [comment]
Can you please add yourself as a maintainer?

**Comment by duncanmmacleod** [comment]
> Can you please add yourself as a maintainer?

I was afraid someone might ask that, I'll do it now. I know nothing about qt...

**Comment by duncanmmacleod** [comment]
@isuruf, done, what happens now?

**Comment by chrisburr** [comment]
I've started the Linux build and I'll do the macOS one overnight.

@isuruf Will you take care of the Windows build or would you rather I guide @duncanmmacleod with it?

**Comment by chrisburr** [comment]
I see @isuruf already built the Windows binaries, thanks! 🍰 

Logs for the unix builds are (compressed with `zstd`):
* [linux_64_.zst.log](https://github.com/conda-forge/qt-feedstock/files/6014851/linux_64_.zst.log)
* [osx_64_.zst.log](https://github.com/conda-forge/qt-feedstock/files/6014852/osx_64_.zst.log)

**Comment by duncanmmacleod** [comment]
Just to confirm, this has resolved my environment issue. Many thanks to @isuruf and @chrisburr!

**Pull request merged**
