### PR TITLE
Update to 5.15.0 (WIP)

### PR DESCRIPTION
**Pull request by mingwandroid**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mingwandroid** [comment]
So far, I have managed to build this for Windows locally.

**Comment by jschueller** [comment]
hello, any news on this ?

**Comment by mingwandroid** [comment]
Not much from my side. I push new commits when i can though. Progress is being made but slowly.

**Comment by mingwandroid** [comment]
Not to this branch mind you ..

**Comment by jschueller** [comment]
oh ok, thanks

**Comment by Tobias-Fischer** [comment]
See https://github.com/conda-forge/qt-feedstock/pull/206

**Pull request closed without merging**
