### PR TITLE
Repin with Gstreamer 1.14

### PR DESCRIPTION
**Pull request by croth1**
…nda-forge-pinning 2019.01.29

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by croth1** [comment]
Wow, conda went back straight to the last ice age to dig out this amazing curl version: 🙄 

`curl                      7.49.1                        0    conda-forge`

**Comment by looooo** [comment]
curl 7.49.1 0 conda-forge has no openssl version specified. So it's the newest conda-forge curl-package that should work with openssl 1.1.1 (but actually does not). Maybe this old curl-package should be labeled "broken"

**Comment by ccordoba12** [comment]
So, is Qt broken due to the update to Gstreamer to 1.14? Or why is this rebuild needed?

**Comment by croth1** [comment]
gstreamer 1.12 didn't get the glib 2.58 upgrade, and we decided to advance the pin here: https://github.com/conda-forge/gstreamer-feedstock/issues/23

**Comment by ccordoba12** [comment]
Well, I disagree with @scopatz because it'd be far more easier (from the Qt point of view) to simply recompile Gstreamer 1.12 with the new Glib since that doesn't require a rebuild here.

@scopatz, what do you say?

**Comment by ccordoba12** [comment]
Besides, this Qt version is very old so it could not be compatible with Gstreamer 1.14

**Comment by croth1** [comment]
@ccordoba12 @scopatz  @isuruf, @conda-forge/core we should really, really start drafting a common strategy on how pins are chosen and advanced. Things are confusing and messy right now.

**Comment by croth1** [comment]
1.14 is very likely to be compatible because macOS already builds with 1.14. 

Rebuilding 1.12 will require at least some work, because gstreamer and gst-plugin-base were merged some time after 1.12 and there is no LTS branch for the 1.12.x series.

**Comment by scopatz** [comment]
There's a lot of confusion about which ABI gstreamer earlier versions was built with. It is probably easier to just rebuild.

**Comment by ccordoba12** [comment]
> 1.14 is very likely to be compatible because macOS already builds with 1.14.

Good point. Then you'll haver to sort the difficulties on Linux, sorry.

**Comment by ccordoba12** [comment]
Ok, this looks good to go. Thanks @isuruf for your help with the last commit.

**Pull request merged**
