### PR TITLE
Fix harcoded sysroot paths

### LINKED ISSUE #123: v5.12.5: Qt5GuiConfigExtras.cmake hardcodes path to libEGL.so cdt
updating to 5.12.5 I got build failures for pyside2 because Qt5GuiConfigExtras.cmake hardcodes the path to libEGL.so:
```
$PREFIX/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:85:_qt5gui_find_extra_libs(EGL "$PREFIX/bin/../x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64/libEGL.so" "" "$PREFIX/include;$PREFIX/x86_64-conda_cos6-linux-gnu/sysroot/usr/include;$PREFIX/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/libdrm;$PREFIX/x86_64-conda_cos6-linux-gnu/sysroot/usr/include")
```
I guess it was automatically changed from build env to host env, but obviously I dont want to add cdt packages to host only build env in the pyside recipe, am I right ?

The same could apply to opengl libs:
upstream is: https://github.com/qt/qtbase/blob/5.12.5/src/gui/Qt5GuiConfigExtras.cmake.in

### PR DESCRIPTION
**Pull request by jschueller**
Closes #123

### CODE REVIEW

**Comment by ocefpaf** [comment]
@mingwandroid do you know how much free space you used in your Windows build? I had ~90 G and it was not enough!! I wonder if I was close or if I should just give up Windows builds of `qt` with my laptop.

**Comment by jschueller** [comment]
any volunteer for another build ?

**Comment by msarahan** [comment]
@isuruf @mingwandroid  what is the status of the win SDK issue? Can we use any SDK now it are we sick with matching what is on azure? I'd like to get to the bottom of that issue before we commence any further builds, but I'm happy to run builds on my machine whenever.

**Comment by mingwandroid** [comment]
I performed the builds for conda-forge on my own machine using the SDK @isuruf requested here https://github.com/conda-forge/qt-feedstock/pull/122#issuecomment-533750190

I had to change the recipe as follows though:

```
diff --git a/recipe/bld.bat b/recipe/bld.bat
old mode 100644
new mode 100755
index e27ff72..41794a0
--- a/recipe/bld.bat
+++ b/recipe/bld.bat
@@ -27,6 +27,8 @@ if exist config.cache del config.cache
 set WEBBACKEND=qtwebengine
 set QT_LIBINFIX=_conda
 
+CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat" x64 10.0.17763.0
+
```

**Comment by mingwandroid** [comment]
Also I didn't try a Win-32 build.

**Comment by isuruf** [comment]
> Can we use any SDK now or are we stuck with matching what is on azure? 

Unfortunately no. Qt somehow hardcodes the path to `shell32.lib` which is in the Win SDK, so dependent libs like `PyQt` have to use the same SDK. To debug this, try grepping for shell32.lib in the built package and see exactly where the path is recorded.

**Comment by isuruf** [comment]
Btw, this PR doesn't affect windows right?

**Comment by jschueller** [comment]
@isuruf only Linux

**Comment by ocefpaf** [comment]
Can we fold this into #127 so we can do a single build later?

**Comment by jschueller** [comment]
@ocefpaf I can rerender here so #127 is unneeded

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by jschueller** [comment]
@conda-forge/qt could this be merged ?

**Comment by isuruf** [comment]
@jschueller, do you know why the tests fail instead of timing out?

**Comment by jschueller** [comment]
oh right, I did not see that error:
```
2019-10-14T18:02:42.3668700Z Undefined symbols for architecture x86_64:
2019-10-14T18:02:42.3670080Z   "___isOSVersionAtLeast", referenced from:
2019-10-14T18:02:42.3736520Z       qt_mac_createSystemPalette() in qcocoasystemsettings.o
2019-10-14T18:02:42.3736980Z       qt_mac_createRolePalettes() in qcocoasystemsettings.o
```

**Comment by jschueller** [comment]
Let's try without the rerender

**Comment by isuruf** [comment]
Try reverting https://github.com/conda-forge/qt-feedstock/pull/125

**Comment by isuruf** [comment]
This is an issue with our compiler-rt package. I'll fix it soon.

**Comment by ocefpaf** [comment]
> This is an issue with our compiler-rt package. I'll fix it soon.

Glad you found the root of the issue. I'd rather keep things "re-rendered" so we ensure that what we are recommending/using is working.

**Pull request merged**
