### PR TITLE
Windows build

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gillins** [comment]
> I'll ping them

That would be great. I haven't had any luck with `vc9` - VS 2008 Express is 32 bit only. Seems conda-build is really only trying to support AppVeyor (not local builds) now that they have dropped support for VS For Python 2.7 (which was 32 and 64 bit).

**Comment by ocefpaf** [comment]
> Seems conda-build is really only trying to support AppVeyor

I don't think that is true b/c their main use is non-AppVeyor (`conda-forge` on the other hand is virtually 100% focused on AppVeyor). But things did change quite a bit and maybe @msarahan can shed some light.

PS: I'll keep you in the look if AppVeyor say something about extending our time here.

**Comment by isuruf** [comment]
Btw, appveyor increased time limit from 60 to 90 minutes for conda-forge a month before and I don't think they increase the limit more than 90 minutes

**Comment by isuruf** [comment]
@jakirkham, isn't the timeout specified for an appveyor organization?

**Comment by jakirkham** [comment]
I don't know. Easy to test though.

**Pull request closed without merging**
