### PR TITLE
is dbus required on linux at runtime?

### PR DESCRIPTION
**Pull request by hmaarrfk**
@conda-forge-admin please rerender
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mingwandroid** [comment]
If you want the QtDBus module I think it is: https://doc.qt.io/qt-5/qtdbus-index.html

This module is frequently used within the Qt ecosystem for Qt programs to communicate with each other. What are you hoping to use as a backend for QtDBus? Internal, vendored dbus code? Is there any? What benefit would that serve us to not use our shared libraries?

**Comment by hmaarrfk** [comment]
Mostly just looking at some odd dependencies in my environments. 

I thought that dbus would have to be the system dbus since it is a system library. I guess not.

**Comment by mingwandroid** [comment]
It's sometimes a system library, but not so much. systemd has its own implementation for system things these days and they wanted to move that into the kernel. DBus is just a communication protocol really.

**Comment by hmaarrfk** [comment]
Is conda relying on the working dbus-daemon of the operating system?

```
> ps aux | grep dbus                                            (mcam_dev) 
message+     702  0.1  0.0  10212  5488 ?        Ss   Sep18   7:05 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root         748  0.0  0.0 134492  6848 ?        Ssl  Sep18   0:45 /usr/sbin/thermald --no-daemon --dbus-enable
mark        2250  0.0  0.0   9072  4800 ?        Ss   Sep18   0:35 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
mark        2492  0.0  0.0   7356  3024 ?        S    Sep18   0:08 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
mark      683623  0.0  0.0  17664   672 pts/2    S+   13:37   0:00 grep --color=auto dbus

```

**Comment by mingwandroid** [comment]
no

**Comment by mingwandroid** [comment]
At least QtDBus is not. It's just a comms / serialization library for Qt. Desktop environments often use dbus to hook up desktop components.

**Comment by mingwandroid** [comment]
> Is conda relying

Where does conda come into this? No. It isn't.

**Comment by hmaarrfk** [comment]
I meant programs compiled with dbus in a conda environment.

Thx again for the super detailed explination. I always get to learn more about how these systems play with each other from you!

**Pull request closed without merging**
