### PR TITLE
Update to 5.15.0

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
some issues:
- chromium builds itself on /tmp which fails on docker
- an issue with the required xcode 10 version
- missing cdt packages
- chromimum requires python2 but cannot be coinstalled so it must be move to a custom prefix

**Comment by looooo** [comment]
@jschueller can you remember which cdt's were missing? logfiles are not available anymore.

**Comment by jschueller** [comment]
you can see these in the diff of meta.yaml

**Comment by looooo** [comment]
> you can see these in the diff of meta.yaml

I understand. Not sure if I can help. I tried to build for linux locally but it was failing with a linking error of gn (missing clock_gettime).

**Comment by jschueller** [comment]
yes, there are many issues, see https://github.com/conda-forge/qt-feedstock/pull/156#issuecomment-634635843

**Comment by mingwandroid** [comment]
I am working on the Qt 5.15.0 update for Anaconda Distribution at the moment.

Feel free to see where I am up to (or help out) at https://github.com/AnacondaRecipes/qt-feedstock (master branch).

So far I have rebased the qtbase patches.

**Comment by jschueller** [comment]
@mingwandroid you can probably use my first steps (missing cdt packages, python2 local install etc)

**Comment by mingwandroid** [comment]
Thanks! I'll definitely check it out, maybe rebase on it?

**Comment by jschueller** [comment]
@mingwandroid seems you've advanced well on the 5.15 update, how far have you been ?
did you have issues with mismatching protobuf versions like I did ?

**Comment by mattip** [comment]
It seems the 5.15.0 version was merged to  https://github.com/AnacondaRecipes/qt-feedstock , but I do not see version 5.15.0 as an [option for downloading](https://anaconda.org/search?q=qt). What else needs to be done?

**Comment by ccordoba12** [comment]
@mattip, the Spyder team is working on updating Qt to 5.15 right now, as discussed in the last comments on issue #192.

Unfortunately, we haven't been able to reach an agreement with the Conda-forge community to split Qt into two packages. That's the last thing to be decided because packages are ready.

**Comment by mattip** [comment]
Maybe some synchronous communication at the [biweekly conda-forge zoom meeting](https://conda-forge.org/docs/orga/minutes/2021-06-16.html) (which I think will be June 30) would help move it forward?

**Comment by ccordoba12** [comment]
Good thinking! Isuru let us know about it a couple of days ago, so we plan to attend to this week's meeting.

**Pull request closed without merging**
