### PR TITLE
Update recipe

### PR DESCRIPTION
**Pull request by ocefpaf**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by ocefpaf** [comment]
> Any thoughts on updating to 5.9.5?

I want to get there but I'm accessing that needs to get rebuild with the new pins first, like `freetype` for example.

> We've done that on AD but rstudio forces us to also update qt 5.6 every so often (which I recently updated to 5.6.3 on mac and Linux).

Sorry to hear that, I would like for conda-forge to have at least qt 5.9

**Comment by mingwandroid** [comment]
If you want to jump to 5.6.3 my work is here: https://github.com/AnacondaRecipes/qt-feedstock/tree/master-5.6.3/recipe

**Comment by mingwandroid** [comment]
.. it shouldn't be too bad (famous last words, when is Qt ever easy?)

**Comment by ocefpaf** [comment]
> .. it shouldn't be too bad (famous last words, when is Qt ever easy?)

:rofl:

**Comment by isuruf** [comment]
Can you cancel https://circleci.com/gh/ocefpaf/qt-feedstock/71?

**Comment by ocefpaf** [comment]
> Can you cancel circleci.com/gh/ocefpaf/qt-feedstock/71?

Done.

**Comment by ocefpaf** [comment]
Let's go with #69. Thanks @isuruf!

**Pull request closed without merging**
