### PR TITLE
Fix Windows build

### PR DESCRIPTION
**Pull request by ocefpaf**
Trying to finish #102

### CODE REVIEW

**Comment by ocefpaf** [comment]
My local build, and one of the Azure tries in #102, failed with:


```
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\src\angle\src\libGLESv2\Makefile [release] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\src\angle\src\Makefile [sub-libGLESv2-release_ordered] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\src\angle\Makefile [sub-src-release] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\src\Makefile [sub-angle-release] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\src\Makefile [sub-corelib-release] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\Makefile [sub-src-release] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\Makefile [module-qtbase-release] Error 2
```

When I build it locally it first complained about a missing `qmake`, I installed the current version of `qt` and tried again and the build goes until the error above. Does that make sense @gillins? How do you circumvent the lack of `qmake` in your machine?

**Comment by ocefpaf** [comment]
Pinging @mingwandroid and @isuruf here too, any insight you can give on building `qt` on Windows will be very helpful!

**Comment by gillins** [comment]
qmake got created as part of the build for me so i didn't have to do anything else. I didn't get that other error. You have VS 2015 installed on your machine?

**Comment by ocefpaf** [comment]
> qmake got created as part of the build for me

That is what I expected would happen :-/

> You have VS 2015 installed on your machine?

Probably not then. I'll remove what I have and re-install it. Thanks!

**Comment by ocefpaf** [comment]
@gillins and @msarahan I had that community VS version. What is the recommend one to build conda packages nowadays? I Google VS 2015 but ended up in a dead end in https://my.visualstudio.com/Downloads?q=visual%20studio%202015&wt.mc_id=o~msft~vscom~older-downloads

**Comment by tadeu** [comment]
@ocefpaf, awesome to know that Qt is being updated! :D

At the end of this page there is a "Still want Visual Studio Express" section, where "Express 2015 for Windows Desktop" can be found: https://visualstudio.microsoft.com/vs/express/

**Comment by ocefpaf** [comment]
Thanks @tadeu! I try that soon and report back.

**Comment by ocefpaf** [comment]
> At the end of this page there is a "Still want Visual Studio Express" section, where "Express 2015 for Windows Desktop" can be found: https://visualstudio.microsoft.com/vs/express/

It goes to the same dead end 😄 

Trying the community version again.

**Comment by gillins** [comment]
Does it take you to a login screen? I think you need a Microsoft ID to download anything these days...

If it is installed successfully you should have a bunch of files under `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC` (I'd be a bit cautious about installing in anything other than the default location).

When you are running the installer make sure you select C++ as I have a feeling it isn't checked by default.

**Comment by ocefpaf** [comment]
> Does it take you to a login screen? I think you need a Microsoft ID to download anything these days...

Could be.

> If it is installed successfully you should have a bunch of files under `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC` (I'd be a bit cautious about installing in anything other than the default location).
> 
> When you are running the installer make sure you select C++ as I have a feeling it isn't checked by default.

I think I got it right with the community edition yesterday but the build did not end b/c Windows, against my configuration, decided to put the laptop to sleep. I'm trying again this morning, I think it will work. (At some point yesterday I got the same error as you when copying the post file, I'm creating the folder now before copying. Fingers crossed.)

**Comment by ocefpaf** [comment]
I got a successful build on Windows :tada: 

Please let me know if you find any problem with it, the build is: https://anaconda.org/conda-forge/qt/5.9.7/download/win-64/qt-5.9.7-hc6833c9_1.tar.bz2

This was the last step to sync with AnacondaRecipes and to complete the `openssl` migration. Thanks to all who contribute to PRs #88, #91, #98, and #102 (@hmaarrfk, @tadeu, @gillins, @marcelotrevisani, @mariusvniekerk, @mingwandroid, and @isuruf)!

**Comment by ccordoba12** [comment]
Nice!! Thanks a lot for your help @ocefpaf!

**Comment by tadeu** [comment]
Awesome! :D 

I'm testing it locally, I've noticed that it is using a dependency from `pkgs/main` that is not yet in conda-forge:

```
vs2015_runtime           14.15.26706      h3a45250_0  pkgs/main
```

should this package be added to conda-forge?

**Comment by ocefpaf** [comment]
> should this package be added to conda-forge?

In theory we don't need to. With `strict` channel enabled you should get that one from `defaults` and the rest of from conda-forge without a problem. We, conda-forge, decided to not package the compilers run time at the moment.

**Comment by hmaarrfk** [comment]
Did this ever build on a CI?

I'm getting strange errors on opencv trying to import cv2, which I assume is due to a qt issue?

https://github.com/conda-forge/opencv-feedstock/pull/160

**Comment by ocefpaf** [comment]
> Did this ever build on a CI?

Only macOS.
 
> I'm getting strange errors on opencv trying to import cv2, which I assume is due to a qt issue?

The version that hopefully "fixes" Windows was uploaded a few minutes ago. Can you please try again in ~30 min (until the index updates).

**Comment by hmaarrfk** [comment]
Ah, got it, thanks! Will try.

**Pull request merged**
