### PR TITLE
[WIP] - Upgrade qt version and migrate to conda build 3

### PR DESCRIPTION
**Pull request by marcelotrevisani**

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
I was trying to update the ``qt`` version to ``5.11.1``. However, ``conda`` is failing to unpack the file.

cc: @ocefpaf @conda-forge/qt

**Comment by mingwandroid** [comment]
Should we not stick to an LTS release here? Updating Qt frequently is hugely painful!

**Comment by ocefpaf** [comment]
@mingwandroid it is correct that it is quite painful but I'm not against people trying it and, if successful, adding it to conda-forge. That is the whole reason we created conda-forge, so people can test the latest packages. Those looking for stability always have `defaults` :wink:

With that said... I don't really want to put my hands in Qt right now. It requires a lot of effort and I don't have the time.

**Comment by marcelotrevisani** [comment]
@mingwandroid , Oh sorry, it's not my intention to rebuild that a lot of times, just to show the problem which I'm facing. As I expected it failed just in the begging when conda tried to unpack the file.

As you can see by the log

```
source tree in: /feedstock_root/build_artefacts/qt_1530528711936/work/qt-everywhere-src-5.11.1
+ source /opt/conda/bin/activate /feedstock_root/build_artefacts/qt_1530528711936/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
+ chmod +x configure
++ uname
+ '[' Linux == Linux ']'
+ curl http://linorg.usp.br/Qt/community_releases/5.6/5.11.1/qtwebkit-opensource-src-5.11.1.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   611  100   611    0     0    762      0 --:--:-- --:--:-- --:--:--   761
+ unxz qtwebkit.tar.xz
unxz: qtwebkit.tar.xz: File format not recognized
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1524, in build_tree
    config=config)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1147, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 628, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/utils.py", line 624, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/feedstock_root/build_artefacts/qt_1530528711936/work/qt-everywhere-src-5.11.1/conda_build.sh']' returned non-zero exit status 1.
```

**Comment by mingwandroid** [comment]
I cannot personally help to maintain two sets of Qt packages so if CF moves to Qt > 5.9 I will be unable to help out.

**Comment by ocefpaf** [comment]
> I cannot personally help to maintain two sets of Qt package recipes so if CF moves to Qt > 5.9 I will be unable to help out.

We should create a branch for 5.9 to keep that one in sync.

**Comment by looooo** [comment]
PySide2 release doesn't support qt5.9. So in my eyes it would be really nice to have qt5.11 package build with condaforge deps.

**Comment by mingwandroid** [comment]
These are good arguments. Still I think 5.12 will be the next LTS release so AD will probably prefer to wait for that.

**Comment by ccordoba12** [comment]
> PySide2 release doesn't support qt5.9. So in my eyes it would be really nice to have qt5.11 package build with condaforge deps

If you're willing to invest 50 to 100 hours (perhaps more) compiling Qt in all platforms (because it can't be compiled in our CIs), then please go for it.

**Comment by looooo** [comment]
Yes, waiting for 5.12 is a good idea. Release in November. Maybe we can prepare for this release by trying to update the qt-feedstock to qt5.11? No idea if this makes sense.

> If you're willing to invest 50 to 100 hours (perhaps more) compiling Qt in all platforms (because it can't be compiled in our CIs), then please go for it.

Yes, I believe packaging qt is a really hard job. The only thing I can offer are test-builds on Linux and windows.

**Comment by marcelotrevisani** [comment]
I can give a try for ``qt 5.11`` (for linux platform at least). However, I'm facing this error when I tried to build using ``conda build`` which is not possible to unpack the source package.

Does anyone know how to solve that?

**Comment by gillins** [comment]
It's the package for webkit that gets built at the same time that is causing the problem. It doesn't seem to be available for Qt 5.11?

Is the latest plan to move to webengine instead?

**Comment by mingwandroid** [comment]
In defaults we've moved to webengine where possible which is everywhere that qt 5.9.5 and above works (so all but Windows Python 2).

**Comment by looooo** [comment]
maybe we should disable webkit and webengine for now?

@mingwandroid Do you think it's possible to build qt5.9/5.11 with the current conda-forge infrastructure? (gcc4.8.5)

**Comment by mingwandroid** [comment]
No it is not.

**Comment by looooo** [comment]
What is the show-stopper? qt lists gcc4.8 [here](https://doc.qt.io/qt-5/supported-platforms-and-configurations.html)

**Comment by mingwandroid** [comment]
Well in defaults because we use the new c++ abi exclusively we cannot use GCC 4.8. For cf I don't know but they need to get I'd such old toolchains. I seriously doubt qt will compile ok with GCC 4.8 too despite the page you linked to also not something I can find time on as GCC 4.8 needs to be dropped ASAP.

AFAIK conda-forge stopped building qt due to time restrictions in ci and started to use our packages. That's probably less possible now we're using new compilers though.

**Comment by jakirkham** [comment]
IIUC people were building `qt` locally and uploading it to the `conda-forge` channel.

**Comment by looooo** [comment]
ok, so I guess there is no known show-stopper for qt5.9 /qt5.11 with the current conda-forge toolchain. But it doesn't mean it will work. And for sure it is way too complex to get done in a week or so.

Another option is to use defaults qt in qt-dependent packages (mixing packages compiled with different versions of gcc) Would this work?

**Comment by ocefpaf** [comment]
@marcelotrevisani due to the high complexity of `qt` I  recommend to start this one over based on #69, which we'll merge in a moment.

**Comment by mingwandroid** [comment]
For me I am considering providing a QtWebKit package for whatever the latest qt version I package is.

**Comment by ccordoba12** [comment]
> For me I am considering providing a QtWebKit package for whatever the latest qt version I package is.

This sounds great Ray! It'll help people with the frustrating errors QtWebEngine has on Linux and Windows due to its reliance in OpenGL.

**Comment by ccordoba12** [comment]
Closing this one per #69.

**Comment by gillins** [comment]
> For me I am considering providing a QtWebKit package for whatever the latest qt version I package is.

We already have one of these: https://github.com/conda-forge/qtwebkit-feedstock :smile:

**Comment by mingwandroid** [comment]
I know, I forked and updated it for 5.9.5.

**Comment by ccordoba12** [comment]
When do you plan to upload new packages for it Ray?

**Comment by mingwandroid** [comment]
I'm still building out Python 3.7 for Windows. Hopefully soon though.

**Pull request closed without merging**
