### PR TITLE
Sync with AnacondaRecipes (5.15)

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mingwandroid** [comment]
Happy for any assistance getting this done! I will keep pushing to AR master.

**Comment by xhochy** [comment]
Progress here will be very slow, I don't need this immediately, I only want to unblock the `icu` migration. For now, I've added the missing CDTs: https://github.com/conda-forge/cdt-builds/pull/19

**Comment by jcarpent** [comment]
Hi @xhochy,

I would be interested in Qt 5.15. Do you have a timeline in mind to release it?
Best,

Justin

**Comment by Tobias-Fischer** [comment]
See https://github.com/conda-forge/qt-feedstock/pull/206

**Pull request closed without merging**
