### PR TITLE
Conda build 2

### PR DESCRIPTION
**Pull request by ocefpaf**
Note to self: a quick test on Travis-CI with `j 2` still resulted in a test timeout.

```
cd "/Users/travis/miniconda3/conda-bld/recipe_1483010385751/work/qt-everywhere-opensource-src-4.8.7/./tools/linguist/lconvert"

/Applications/Xcode.app/Contents/Developer/usr/bin/make Makefile

make[4]: `Makefile' is up to date.

compiling ../shared/numerus.cpp

compiling ../shared/translator.cpp

compiling ../shared/translatormessage.cpp

compiling ../shared/qm.cpp



The job exceeded the maximum time limit for jobs, and has been terminated.
```

### CODE REVIEW

**Comment by ocefpaf** [comment]
A quick test on Travis-CI with `j 2` still resulted in a test timeout.

```
cd "/Users/travis/miniconda3/conda-bld/recipe_1483010385751/work/qt-everywhere-opensource-src-4.8.7/./tools/linguist/lconvert"

/Applications/Xcode.app/Contents/Developer/usr/bin/make Makefile

make[4]: `Makefile' is up to date.

compiling ../shared/numerus.cpp

compiling ../shared/translator.cpp

compiling ../shared/translatormessage.cpp

compiling ../shared/qm.cpp



The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by ccordoba12** [comment]
@ocefpaf, please disable osx ASAP. People are sending more PRs here  (see #21) and we're just wasting resources not just for the entire organization but for all Github projects, given that Travis only has 128 macOS workers available.

**Comment by gillins** [comment]
> j 2 still resulted in a test timeout.

That is frustrating - it must be very close to finishing....

**Comment by ocefpaf** [comment]
> @ocefpaf, please disable osx ASAP. 

I cannot when I am using it for testing :wink: 

I am collecting some data to write them again and ask for more time.
It worked with AppVeyor so it is worth a chance.
Besides it is not a big deal as AppVeyor build because we do have concurrence on Travis-CI.
(In AppVeyor a single feedstock can block everything after it though.)

> That is frustrating - it must be very close to finishing....

Indeed.

**Comment by ccordoba12** [comment]
Thanks for skipping osx and sorry for being so insisting with it. The thing is I've sat to wait for Travis to give me a slot for more than an hour (on the Spyder org, not here) and that's just a nightmare when you're in a hurry ;-p

**Comment by ocefpaf** [comment]
I know the pain :smile: I've been building dependencies that depends on  `gdal` and `qt`for the past few days :smile:

**Pull request merged**
