### PR TITLE
BUG add ld64

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
This change was needed to build qt locally on my mac. I am adding it here for posterity.

**Comment by beckermr** [comment]
@isuruf can you take a look?

We don't need a build number bump here.

**Comment by mingwandroid** [comment]
Why isn't this getting pulled in as a dependency of the compiler?

**Comment by beckermr** [comment]
Good question.

**Comment by beckermr** [comment]
Here is the build env w/ ld64

```
    cctools_osx-64:     949.0.1-h5ba7a2e_7        conda-forge
    clang:              10.0.1-default_hf57f61e_1 conda-forge
    clang_osx-64:       10.0.1-h05bbb7f_8         conda-forge
    clangxx:            10.0.1-default_hf57f61e_1 conda-forge
    clangxx_osx-64:     10.0.1-h05bbb7f_8         conda-forge
    compiler-rt:        10.0.1-he6db49b_0         conda-forge
    compiler-rt_osx-64: 10.0.1-h033240e_0         conda-forge
    ld64:               530-7                     conda-forge
    ld64_osx-64:        530-h3c32e8a_7            conda-forge
    libclang-cpp10:     10.0.1-default_hf57f61e_1 conda-forge
    libcxx:             10.0.1-h5f48129_0         conda-forge
    libiconv:           1.16-haf1e3a3_0           conda-forge
    libllvm10:          10.0.1-h009f743_3         conda-forge
    llvm-tools:         10.0.1-h1341992_3         conda-forge
    make:               4.3-h0b31af3_0            conda-forge
    ninja:              1.10.1-h879752b_1         conda-forge
    perl:               5.30.3-h6156909_1         conda-forge
    pkg-config:         0.29.2-hdc84dc8_1006      conda-forge
    tapi:               1000.10.8-h879752b_4      conda-forge
    zlib:               1.2.11-h7795811_1009      conda-forge
```

and here it is without

```
    cctools_osx-64:     949.0.1-h5ba7a2e_7        conda-forge
    clang:              10.0.1-default_hf57f61e_1 conda-forge
    clang_osx-64:       10.0.1-h05bbb7f_8         conda-forge
    clangxx:            10.0.1-default_hf57f61e_1 conda-forge
    clangxx_osx-64:     10.0.1-h05bbb7f_8         conda-forge
    compiler-rt:        10.0.1-he6db49b_0         conda-forge
    compiler-rt_osx-64: 10.0.1-h033240e_0         conda-forge
    ld64_osx-64:        530-h3c32e8a_7            conda-forge
    libclang-cpp10:     10.0.1-default_hf57f61e_1 conda-forge
    libcxx:             10.0.1-h5f48129_0         conda-forge
    libiconv:           1.16-haf1e3a3_0           conda-forge
    libllvm10:          10.0.1-h009f743_3         conda-forge
    llvm-tools:         10.0.1-h1341992_3         conda-forge
    make:               4.3-h0b31af3_0            conda-forge
    ninja:              1.10.1-h879752b_1         conda-forge
    perl:               5.30.3-h6156909_1         conda-forge
    pkg-config:         0.29.2-hdc84dc8_1006      conda-forge
    tapi:               1000.10.8-h879752b_4      conda-forge
    zlib:               1.2.11-h7795811_1009      conda-forge
```

IDK the difference between `ld64` and `ld64_osx-64` or what having both in one env will do.

**Comment by mingwandroid** [comment]
ld64_osx-64 should depend on ld64 I think!

**Comment by beckermr** [comment]
I only see a dependence on `ld` which I cannot actually find as a package anywhere...

**Comment by isuruf** [comment]
`ld64_osx-64` has only the prefixed tools like `x86_64-apple-darwin13.4.0-ld`.
`ld64` has `ld64_osx-64` as a run requirement, but also has `ld->x86_64-apple-darwin13.4.0-ld` symlink.
I think we can add `ld64` package to `clang_osx-64` when it's a native compiler.

**Comment by isuruf** [comment]
Issue here is that `qt` is using `clang` instead of `x86_64-apple-darwin13.4.0-clang`. Only the latter knows to use `x86_64-apple-darwin13.4.0-ld` while the former only looks for `ld`.

**Comment by beckermr** [comment]
> I think we can add ld64 package to clang_osx-64 when it's a native compiler.

Cool. See here: https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/34

I am going to close this PR assuming the change to clang gets merged.

**Pull request closed without merging**
