### PR TITLE
Test

### PR DESCRIPTION
**Pull request by ocefpaf**
If this works it is an alternative to #88 and closes #98, #97 and #91.

### CODE REVIEW

**Comment by ocefpaf** [comment]
macOS error:

```
WARNING: You asked me to use /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk as the MacOS SDK
         But because of the use of Objective-C Generics we need at
         least MacOSX10.11.sdk
ERROR: /opt/MacOSX10.11.sdk is not a directory
```

Testing 10.11 now...

**Comment by ocefpaf** [comment]
Linux passed locally and I'll try Windows later today on another machine.

@isuruf and @mingwandroid any idea of what is going on with macOS here?

@isuruf is there anything I should be careful when building on Windows if we decide to upload it later to the channel?

PS: any volunteers to build macOS ;-p

**Comment by ccordoba12** [comment]
@mariusvniekerk made the macOS build pass in Azure by using the 10.12 SDK, so I think we should use what he did and disable Linux and Windows for now.

**Comment by ocefpaf** [comment]
> @mariusvniekerk made the macOS build pass in Azure by using the 10.12 SDK

I'll check the extra config nobs with @mariusvniekerk later about macOS.

> so I think we should use what he did and disable Linux and Windows for now.

Nope. Let's keep them enable so we at least know they are blowing up due to time instead of something else. Also it will help make the case to request more resources.

**Comment by ccordoba12** [comment]
> Nope. Let's keep them enable so we at least know they are blowing up due to time instead of something else. Also it will help make the case to request more resources.

Ok, :+1:

**Comment by ocefpaf** [comment]
Windows build got stuck in Azure at:

```
[12124/18071] CXX obj/components/spellcheck/browser/browser/feedback.obj
jom terminated by user (pid=2912)
jom terminated by user (pid=1828)
jom terminated by user (pid=3832)
jom terminated by user (pid=3308)
jom terminated by user (pid=704)
jom: C:\bld\qt_1555979329571\work\Makefile [module-qtwebengine-release] Error 2
jom terminated by user (pid=4832)
The process tried to write to a nonexistent pipe.
The process tried to write to a nonexistent pipe.
The process tried to write to a nonexistent pipe.
The process tried to write to a nonexistent pipe.
The process tried to write to a nonexistent pipe.
The process tried to write to a nonexistent pipe.

jom 1.1.3 - empower your cores

Terminate batch job (Y/N)? 
##[error]The operation was canceled.
```

I'm trying locally but I'm getting an "`qmake not found`" error right at the beginning. Not sure what is wrong with my configuration.

@gillins do you have any advice for me on how to build that on Windows?

**Comment by ocefpaf** [comment]
Update on OS X. The build completed but failed with:

```
+DEBUG_CXXFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -Og -g -Wall -Wextra -I$PREFIX/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix
Info: creating stash file $SRC_DIR/test/.qmake.stash
$PREFIX/bin/x86_64-apple-darwin13.4.0-clang++ -c -pipe -stdlib=libc++ -O2 -std=gnu++11  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/qt -I../../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/qt/QtCharts -I../../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/qt/QtWidgets -I../../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/qt/QtGui -I../../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/include/qt/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/mkspecs/macx-clang -o main.o main.cpp
$PREFIX/bin/x86_64-apple-darwin13.4.0-clang++ -stdlib=libc++ -headerpad_max_install_names  -arch x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,$PREFIX/lib -o hello main.o   -lQt5Charts -L$PREFIX/lib -framework DiskArbitration -framework IOKit -lQt5Widgets -lQt5Gui -lQt5Core -framework OpenGL -framework AGL 
dyld: Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /usr/local/miniconda/conda-bld/qt_1556040923204/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/libQt5Core.5.dylib
  Reason: image not found
/usr/local/miniconda/conda-bld/qt_1556040923204/test_tmp/run_test.sh: line 12: 92563 Abort trap: 6           ./hello
Tests failed for qt-5.9.7-h93ee506_1.tar.bz2 - moving package to /usr/local/miniconda/conda-bld/broken
WARNING:conda_build.build:Tests failed for qt-5.9.7-h93ee506_1.tar.bz2 - moving package to /usr/local/miniconda/conda-bld/broken
TESTS FAILED: qt-5.9.7-h93ee506_1.tar.bz2
##[error]Bash exited with code '1'.
##[section]Finishing: Build recipe
```

I'll try to re-add `icu` as a run-time dep b/c I believe some of our other deps are pulling it during the build.

**Comment by ocefpaf** [comment]
I got a better machine for Windows and not I can reproduce the error I saw on the last azure log:

```
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\src\angle\src\libGLESv2\Makefile [release] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\src\angle\src\Makefile [sub-libGLESv2-release_ordered] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\src\angle\Makefile [sub-src-release] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\src\Makefile [sub-angle-release] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\src\Makefile [sub-corelib-release] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\qtbase\Makefile [sub-src-release] Error 2
jom: C:\Users\filipe\Miniconda3\envs\BUILD\conda-bld\qt_1556073246940\work\Makefile [module-qtbase-release] Error 2
```

**Comment by gillins** [comment]
> do you have any advice for me on how to build that on Windows?

My only advice is to set a very small `--croot` (ie `c:\qt`) so that the paths don't get too long (I think some tools have trouble with long paths and `qt` has some very long filenames).

I've been running a build locally for ~5 hours so far. Seems to have gotten further than Azure, but I'll keep you posted with the result. BTW I *think* the error you are seeing on Azure is related to the build timing out after 6 hours and processes being terminated, but I'm not certain.

**Comment by ccordoba12** [comment]
Yes, I think there's no error on Windows, the build just times out.

**Comment by ocefpaf** [comment]
Merging this to get macOS in. Linux was manually uploaded already and I'll open a new PR for Windows. Thanks to all worked on PRs  #88, #98, #97 and #91!

**Comment by ocefpaf** [comment]
> Yes, I think there's no error on Windows, the build just times out.

The error is from my local machine. It is not timing out.

> My only advice is to set a very small --croot (ie c:\qt) so that the paths don't get too long (I think some tools have trouble with long paths and qt has some very long filenames).

Thanks. I'll try that today.

> I've been running a build locally for ~5 hours so far.

I got a relatively powerful machine and my builds are 2.5 hours until the error in https://github.com/conda-forge/qt-feedstock/pull/102#issuecomment-486017157

**Comment by gillins** [comment]
OK my build went for about 9 hours and built Qt but failed at the copying `write_qtconf.bat` step (seems the `%PREFIX%\Scripts` folder doesn't exist at this point...). Let me know how you get on with your build, if the shorter croot doesn't work, I'm not sure what else is different between our systems.

**Comment by ocefpaf** [comment]
> OK my build went for about 9 hours

Ouch! And I'm complaining about 2.5 hours :grimacing:
(But I don't always have access to this laptop, it was borrowed just to build `qt`.)

> and built Qt but failed at the copying `write_qtconf.bat` step (seems the `%PREFIX%\Scripts` folder doesn't exist at this point...). Let me know how you get on with your build, if the shorter croot doesn't work, I'm not sure what else is different between our systems.

I'll report back later today. Let's move the Windows discussion to #103

**Pull request merged**
