### PR TITLE
Aarch and PPC64LE

### PR DESCRIPTION
**Pull request by hmaarrfk**
Ensure the following are merged
- [ ] https://github.com/conda-forge/nss-feedstock/pull/24
- [ ] https://github.com/conda-forge/nspr-feedstock/pull/15
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@beckermr Awesome job with the CDT migration. This packages seems to be building.

@mingwandroid I never meant to say that packaging CDTs was not valuable, just that I didn't have time to go through it for an experimental platform for projects of mine.

@isuruf I think this package will likely fail for aarch due to timeout. I think you mentionned you had a plan for building it locally. Was that still an option today (in the coming weeks)?

Needs:

- [ ] https://github.com/conda-forge/mysql-feedstock/pull/18
- [ ] nspr==4.2.0
- [ ] nss==3.39

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by isuruf** [comment]
Send me your ssh public key and I'll add you to the aarch64 server and ppc64le server

**Comment by hmaarrfk** [comment]
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCXtP5+7zPAlLIWarLYMBEvHvCgsUgmnKSysDrBK5/pzQgdrwDzsbl/b9PAqZUwK2+eBhHsIJ20WsWC/emWLY8R3S0YPYaXKDEtx+eix1pVejtw5IcLZtFEcW/kT2KyiGS7qXu+c/zH948AgnSur33rX2VHVLKZtAz+N5Qyie8I+0Hj/O9JfhZZAIqFcGoYcQb1ZuRWbnnpCDjA/ATWip5o0q0DMYjs+vK3IeXu6n93XaTtcaxqeLvTLbJJhZHzDKmTPsgj17EjRTOBwsjagQOPHYrHlNu2B2oTmJ3mXqwWXoBhp/YOG4Efv2aHNBSR++xnbsJFCwLEgy9zZabcgvr/ mark2@xps
```

**Comment by hmaarrfk** [comment]
Failures seem similar between aarch and ppc


drone: `> g++: error: unrecognized command line option '-mrdrnd'`

```
> main.cpp:3:4: error: #error Symbolic function binding on this architecture may be broken, disabling it (see QTBUG-36129).
>  #  error Symbolic function binding on this architecture may be broken, disabling it (see QTBUG-36129).
>     ^~~~~
> make: *** [Makefile:187: main.o] Error 1
test config.qtbase.tests.reduce_relocations FAILED
```

```
> main.o:main.cpp:function main: error: undefined reference to 'dlopen'
> main.o:main.cpp:function main: error: undefined reference to 'dlclose'
> main.o:main.cpp:function main: error: undefined reference to 'dlsym'
> main.o:main.cpp:function main: error: undefined reference to 'dlerror'
> collect2: error: ld returned 1 exit status
```

```
> main.cpp: In function 'int main(int, char**)':
> main.cpp:8:12: error: 'getentropy' was not declared in this scope
>      (void) getentropy(buf, sizeof(buf));
>             ^~~~~~~~~~
> main.cpp:8:12: note: suggested alternative: 'getopt'
>      (void) getentropy(buf, sizeof(buf));
>             ^~~~~~~~~~
>             getopt
> make: *** [Makefile:169: main.o] Error 1
test config.qtbase_corelib.tests.getentropy FAILED
```

```
> main.o:main.cpp:function main: error: undefined reference to 'libiconv_open'
> main.o:main.cpp:function main: error: undefined reference to 'libiconv'
> main.o:main.cpp:function main: error: undefined reference to 'libiconv_close'
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:67: posix_iconv] Error 1
```


travis:

```
> g++ -c -pipe -O2 -w -fPIC -D_X_INLINE=inline -DXK_dead_currency=0xfe6f -D_FORTIFY_SOURCE=2 -DXK_ISO_Level5_Lock=0xfe13 -DFC_WEIGHT_EXTRABLACK=215 -DFC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -DGLX_GLXEXT_PROTOTYPES -I. -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/openssl_hack/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/qtbase/mkspecs/linux-g++ -o main.o main.cpp
> main.cpp: In function 'int main(int, char**)':
> main.cpp:8:12: error: 'getentropy' was not declared in this scope
>      (void) getentropy(buf, sizeof(buf));
>             ^~~~~~~~~~
> main.cpp:8:12: note: suggested alternative: 'getopt'
>      (void) getentropy(buf, sizeof(buf));
>             ^~~~~~~~~~
>             getopt
> make: *** [Makefile:169: main.o] Error 1
test config.qtbase_corelib.tests.getentropy FAILED
```

```
> main.o:main.cpp:function main: error: undefined reference to 'libiconv_open'
> main.o:main.cpp:function main: error: undefined reference to 'libiconv'
> main.o:main.cpp:function main: error: undefined reference to 'libiconv_close'
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:67: posix_iconv] Error 1
 => source failed verification.
test config.qtbase_corelib.libraries.posix_iconv FAILED
```

```
> g++ -c -pipe -O2 -w -fPIC -D_X_INLINE=inline -DXK_dead_currency=0xfe6f -D_FORTIFY_SOURCE=2 -DXK_ISO_Level5_Lock=0xfe13 -DFC_WEIGHT_EXTRABLACK=215 -DFC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -DGLX_GLXEXT_PROTOTYPES -I. -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/openssl_hack/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/qtbase/mkspecs/linux-g++ -o main.o main.cpp
> main.cpp: In function 'int main(int, char**)':
> main.cpp:11:14: error: invalid conversion from 'const char**' to 'char**' [-fpermissive]
>      iconv(x, &inp, &inbytes, &outp, &outbytes);
>               ^~~~
> In file included from main.cpp:2:
> /home/conda/feedstock_root/build_artifacts/qt_1598836670466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include/iconv.h:82:43: note:   initializing argument 2 of 'size_t libiconv(libiconv_t, char**, size_t*, char**, size_t*)'
>  extern size_t iconv (iconv_t cd,  char* * inbuf, size_t *inbytesleft, char* * outbuf, size_t *outbytesleft);
>                                    ~~~~~~~~^~~~~
> make: *** [Makefile:169: main.o] Error 1
```

```
> g++ -c -pipe -O2 -w -fPIC -D_X_INLINE=inline -DXK_dead_currency=0xfe6f -D_FORTIFY_SOURCE=2 -DXK_ISO_Level5_Lock=0xfe13 -DFC_WEIGHT_EXTRABLACK=215 -DFC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -DGLX_GLXEXT_PROTOTYPES -I. -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/openssl_hack/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/qtbase/mkspecs/linux-g++ -o main.o main.cpp
> main.cpp: In function 'int main(int, char**)':
> main.cpp:9:53: error: 'RENAME_NOREPLACE' was not declared in this scope
>      renameat2(AT_FDCWD, argv[1], AT_FDCWD, argv[2], RENAME_NOREPLACE | RENAME_WHITEOUT);
>                                                      ^~~~~~~~~~~~~~~~
> main.cpp:9:72: error: 'RENAME_WHITEOUT' was not declared in this scope
>      renameat2(AT_FDCWD, argv[1], AT_FDCWD, argv[2], RENAME_NOREPLACE | RENAME_WHITEOUT);
>                                                                         ^~~~~~~~~~~~~~~
> main.cpp:9:5: error: 'renameat2' was not declared in this scope
>      renameat2(AT_FDCWD, argv[1], AT_FDCWD, argv[2], RENAME_NOREPLACE | RENAME_WHITEOUT);
>      ^~~~~~~~~
> main.cpp:9:5: note: suggested alternative: 'renameat'
>      renameat2(AT_FDCWD, argv[1], AT_FDCWD, argv[2], RENAME_NOREPLACE | RENAME_WHITEOUT);
>      ^~~~~~~~~
>      renameat
> make: *** [Makefile:169: main.o] Error 1
test config.qtbase_corelib.tests.renameat2 FAILED
```

```
> g++ -c -pipe -O2 -w -fPIC -D_X_INLINE=inline -DXK_dead_currency=0xfe6f -D_FORTIFY_SOURCE=2 -DXK_ISO_Level5_Lock=0xfe13 -DFC_WEIGHT_EXTRABLACK=215 -DFC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -DGLX_GLXEXT_PROTOTYPES -I. -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/openssl_hack/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/qtbase/mkspecs/linux-g++ -o main.o main.cpp
> main.cpp: In function 'int main(int, char**)':
> main.cpp:11:18: error: aggregate 'main(int, char**)::statx statxbuf' has incomplete type and cannot be defined
>      struct statx statxbuf;
>                   ^~~~~~~~
> main.cpp:12:25: error: 'STATX_BASIC_STATS' was not declared in this scope
>      unsigned int mask = STATX_BASIC_STATS;
>                          ^~~~~~~~~~~~~~~~~
> main.cpp:13:32: error: 'AT_STATX_SYNC_AS_STAT' was not declared in this scope
>      return statx(AT_FDCWD, "", AT_STATX_SYNC_AS_STAT, mask, &statxbuf);
>                                 ^~~~~~~~~~~~~~~~~~~~~
> main.cpp:13:70: error: invalid use of incomplete type 'struct main(int, char**)::statx'
>      return statx(AT_FDCWD, "", AT_STATX_SYNC_AS_STAT, mask, &statxbuf);
>                                                                       ^
> main.cpp:11:12: note: forward declaration of 'struct main(int, char**)::statx'
>      struct statx statxbuf;
>             ^~~~~
> make: *** [Makefile:169: main.o] Error 1
test config.qtbase_corelib.tests.statx FAILED
```


```
> /home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/qtdeclarative/config.tests/d3d12/d3d12.cpp:40:10: fatal error: d3d12.h: No such file or directory
>  #include <d3d12.h>
>           ^~~~~~~~~
> compilation terminated.
```

```
> /home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/qtlocation/config.tests/winrt/main.cpp:30:10: fatal error: windows.system.h: No such file or directory
>  #include <windows.system.h>
>           ^~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:169: main.o] Error 1
test config.qtlocation_positioning.tests.winrt_geolocation FAILED
```

```
> g++ -c -pipe -O2 -w -fPIC -D_X_INLINE=inline -DXK_dead_currency=0xfe6f -D_FORTIFY_SOURCE=2 -DXK_ISO_Level5_Lock=0xfe13 -DFC_WEIGHT_EXTRABLACK=215 -DFC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -DGLX_GLXEXT_PROTOTYPES -I. -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/openssl_hack/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/qtbase/mkspecs/linux-g++ -o main.o main.cpp
> main.cpp: In function 'int main(int, char**)':
> main.cpp:12:5: error: 'jpeg_crop_scanline' was not declared in this scope
>      jpeg_crop_scanline(nullptr, &dummy, &dummy);
>      ^~~~~~~~~~~~~~~~~~
> main.cpp:12:5: note: suggested alternative: 'jpeg_read_scanlines'
>      jpeg_crop_scanline(nullptr, &dummy, &dummy);
>      ^~~~~~~~~~~~~~~~~~
>      jpeg_read_scanlines
> main.cpp:13:5: error: 'jpeg_skip_scanlines' was not declared in this scope
>      jpeg_skip_scanlines(nullptr, dummy);
>      ^~~~~~~~~~~~~~~~~~~
> main.cpp:13:5: note: suggested alternative: 'jpeg_read_scanlines'
>      jpeg_skip_scanlines(nullptr, dummy);
>      ^~~~~~~~~~~~~~~~~~~
>      jpeg_read_scanlines
> make: *** [Makefile:172: main.o] Error 1
 => source failed verification.
Trying source 1 (type inline) of library webengine-jpeglib ...
```

```
> g++ -c -pipe -O2 -w -fPIC -D_X_INLINE=inline -DXK_dead_currency=0xfe6f -D_FORTIFY_SOURCE=2 -DXK_ISO_Level5_Lock=0xfe13 -DFC_WEIGHT_EXTRABLACK=215 -DFC_WEIGHT_ULTRABLACK=FC_WEIGHT_EXTRABLACK -DGLX_GLXEXT_PROTOTYPES -I. -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/openssl_hack/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/include -I/home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/qtbase/mkspecs/linux-g++ -o main.o main.cpp
> main.cpp: In function 'int main(int, char**)':
> main.cpp:12:5: error: 'jpeg_crop_scanline' was not declared in this scope
>      jpeg_crop_scanline(nullptr, &dummy, &dummy);
>      ^~~~~~~~~~~~~~~~~~
> main.cpp:12:5: note: suggested alternative: 'jpeg_read_scanlines'
>      jpeg_crop_scanline(nullptr, &dummy, &dummy);
>      ^~~~~~~~~~~~~~~~~~
>      jpeg_read_scanlines
> main.cpp:13:5: error: 'jpeg_skip_scanlines' was not declared in this scope
>      jpeg_skip_scanlines(nullptr, dummy);
>      ^~~~~~~~~~~~~~~~~~~
> main.cpp:13:5: note: suggested alternative: 'jpeg_read_scanlines'
>      jpeg_skip_scanlines(nullptr, dummy);
>      ^~~~~~~~~~~~~~~~~~~
>      jpeg_read_scanlines
> make: *** [Makefile:172: main.o] Error 1
```

```
> Project ERROR: vpx development package not found
test config.qtwebengine_core.tests.webengine-libvpx FAILED
```

```
> /home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/qtwebengine/config.tests/re2/re2.cpp:29:10: fatal error: re2/re2.h: No such file or directory
>  #include <re2/re2.h>
>           ^~~~~~~~~~~
> compilation terminated.
```

```
> /home/conda/feedstock_root/build_artifacts/qt_1598836670466/work/qtwebengine/config.tests/snappy/snappy.cpp:29:10: fatal error: snappy.h: No such file or directory
>  #include <snappy.h>
>           ^~~~~~~~~~
> compilation terminated.
```

```
ERROR: Feature 'reduce_relocations' was enabled, but the pre-condition '!config.win32 && tests.reduce_relocations' failed.
```

**Comment by hmaarrfk** [comment]
Many of the errors above are actually present in the linux x86_64 compilation.

I could not find the error relating to `reduce_relocations`.

**Comment by isuruf** [comment]
Disable `-reduce-relocations` in the build.sh for these platforms?

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
> Disable -reduce-relocations in the build.sh for these platforms?

Thanks for the pointer.

**Comment by hmaarrfk** [comment]
```
ogle_breakpad::user_regs_struct'
   struct user_regs_struct regs;
          ^~~~~~~~~~~~~~~~
../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/dump_writer_common/thread_info.h:70:29: error: field 'fpregs' has incomplete type 'google_breakpad::user_fpsimd_struct'
   struct user_fpsimd_struct fpregs;
                             ^~~~~~
../../3rdparty/chromium/third_party/breakpad/breakpad/src/client/linux/dump_writer_common/thread_info.h:70:10: note: forward declaration of 'struct google_breakpad::user_fpsimd_struct'
   struct user_fpsimd_struct fpregs;
          ^~~~~~~~~~~~~~~~~~

```

**Comment by wolfv** [comment]
@hmaarfk do you have an update on the current state? I was trying to make some ROS packages for AARCH64 and qt is blocking me :) is there anything that I could do to help?

**Comment by hmaarrfk** [comment]
its honestly just a bandwidth issue. I've been a little preoccupied with other weekend activities so I wasn't able to make headway.

**Comment by wolfv** [comment]
sure i totally understand! I was wondering:

a) how do you work on this recipe? Do you / we have a beefy ARM64 machine somewhere?
b) what's missing / can I help?

Most of the other things for the ROS-stack on ARM64 are done now so this is higher up in my priority queue :)

**Comment by mingwandroid** [comment]
> how do you work on this recipe?

You could use a Raspberry pi 4 for this task. It's more or less capable enough. I might have a go with my 5.15.0 WIP work this weekend.

**Comment by mingwandroid** [comment]
With my recipe, on raspi conda-forge-y conda I am missing the following deps:

```
  - fontconfig=2.13
  - libxkbcommon
  - gstreamer=1.14
  - jpeg=9
  - freetype=2.10
  - pthread-stubs
  - clangdev
  - glib=2
  - libxml2=2.9
  - expat=2.2
  - mysql
  - llvmdev
  - sqlite=3
  - libxcb
  - dbus=1
  - gst-plugins-base=1.14
  - zlib=1.2
  - libpng=1.6
  - icu=58
  - nspr
  - postgresql
  - libclang
  - nss
  - flite
```

**Comment by isuruf** [comment]
We have access to a 32-core aarch64 server if anyone wants access to

**Comment by wolfv** [comment]
PM on gitter @isuruf

**Pull request merged**
