### PR TITLE
Update ICU pin

### PR DESCRIPTION
**Pull request by ocefpaf**
cc @mingwandroid

### CODE REVIEW

**Comment by ccordoba12** [comment]
Qt 4 does not depend on ICU, so why is this needed?

**Comment by ccordoba12** [comment]
I mean, ICU is only needed for Qt5 :-)

**Comment by ocefpaf** [comment]
> Qt 4 does not depend on ICU, so why is this needed?

It pulls via `fontconfig` (which in turn pulls it from `libxml2`) and links to it. So it is better to have it explicitly defined here.

This needs two other merges to pass btw.

**Comment by ocefpaf** [comment]
I will wait on https://github.com/conda-forge/fontconfig-feedstock/pull/15 to finish this one.

**Comment by ocefpaf** [comment]
Windows builds are broken :unamused: 

```
(C:\bld\recipe_1486165145723\_b_env) C:\bld\recipe_1486165145723\work\qt-everywhere-opensource-src-4.8.7>cd qt-everywhere-opensource-src-4.8.7 
The system cannot find the path specified.
(C:\bld\recipe_1486165145723\_b_env) C:\bld\recipe_1486165145723\work\qt-everywhere-opensource-src-4.8.7>echo y   | configure.exe -prefix C:\bld\recipe_1486165145723\_b_env\Library                        -libdir C:\bld\recipe_1486165145723\_b_env\Library\lib                        -bindir C:\bld\recipe_1486165145723\_b_env\Library\bin                        -headerdir C:\bld\recipe_1486165145723\_b_env\Library\include\qt                        -datadir C:\bld\recipe_1486165145723\_b_env\Library                        -release                        -shared                        -opensource                        -fast                        -no-qt3support                        -nomake examples                        -nomake demos                        -nomake docs                        -openssl                        -webkit                        -system-zlib                        -system-libpng                        -system-libtiff                        -system-libjpeg 
'configure.exe' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Miniconda35-x64\Scripts\conda-build-script.py", line 5, in <module>
```

I will take a closer look tomorrow.

**Comment by gillins** [comment]
Maybe take out the `cd` line (https://github.com/conda-forge/qt-feedstock/blob/qt4/recipe/bld.bat#L4)? Not sure why this used to work, maybe a change in `conda-build` version? Anyway looks like it is now in that dir already....

**Comment by gillins** [comment]
I don't understand what is going on... There is definitely a configure.exe in that dir. I'll have a better look tomorrow.

**Comment by ocefpaf** [comment]
>  I'll have a better look tomorrow.

Thanks. I will try to steal my wife's laptop and set it up for Windows builds and test this too.

**Comment by gillins** [comment]
OK @ocefpaf this is working for me locally. Turns out the `cd` is a bit of a red herring - it normally fails but the build keeps going (see https://ci.appveyor.com/project/conda-forge/qt-feedstock/build/1.0.31/job/01g6s3if2pxkkrcc#L368 - this previous build worked fine). It would be good to have the `cd` removed though...

Is there a way of clearing out the source cache on AppVeyor?

**Comment by ocefpaf** [comment]
> Is there a way of clearing out the source cache on AppVeyor?

Not sure... I will investigate.

**Comment by ocefpaf** [comment]
I will merge this to get Linux fixed and take care of Windows later,

**Pull request merged**
